### ISSUE TITLE
Options reviving and respawning 

### ISSUE THREAD

**Issue by vinicius7199** [kibook/redm-respawn#1]
I'm testing the script and I noticed that there are no options when I die, only toogle death cam.
[https://imgur.com/a/9vnyyaJ](url)

**Comment by vinicius7199** [comment]
PS: When pressing space bar, the current hud disappears, but the instructions do not appear

**Comment by kibook** [comment]
The revive/respawn options should appear after the cooldown timer reaches 0. In your screenshot, I see the timer is still at 3 seconds. Do the options still not appear after the timer disappears?

Pressing spacebar should make the instructions disappear. Do you mean pressing it again after hiding the HUD does not bring the HUD back?

**Comment by vinicius7199** [comment]
after 3/4 seconds it respawn automatically

**Comment by kibook** [comment]
Ah, I think I see the issue. You need to disable auto-respawn in any other resources (for example, the default basic-gamemode resource):
```lua
exports.spawnmanager.setAutoSpawn(false)
```

**Comment by vinicius7199** [comment]
https://streamable.com/pbre8p

**Comment by vinicius7199** [comment]
Thank you it was this problem, it's working perfectly +rep
